[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rafay-digital-bank"
version = "1.0.0"
description = "A CLI + REST API banking system with SQLite persistence"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "pandas",
]

# !!! ADD THIS PART AT THE BOTTOM !!!
[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]
